#!/usr/bin/env python3
"""Validate an export report generated by the real Magic Resume renderer."""
import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True, type=Path)
    parser.add_argument("--max-pages", required=True, type=int)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    report = json.loads(args.report.read_text(encoding="utf-8"))
    pages = report.get("pdf_pages", report.get("page_count"))
    renderer = str(report.get("renderer", ""))
    artifacts = report.get("artifacts", {})
    failures = []
    if not isinstance(pages, int): failures.append("缺少 PDF 实际页数")
    elif pages > args.max_pages: failures.append(f"页数 {pages} 超过限制 {args.max_pages}")
    if renderer != "isolated-chrome-live-workbench": failures.append("渲染器不是已批准的工作台链路")
    for key in ("preview", "png", "pdf"):
        if not artifacts.get(key): failures.append(f"缺少 {key} 产物路径")
    payload = {"accepted": not failures, "max_pages": args.max_pages,
               "actual_pages": pages, "failures": failures, "report": str(args.report.resolve())}
    destination = args.output or args.report.with_name("validation-report.json")
    destination.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if failures:
        raise SystemExit("; ".join(failures))


if __name__ == "__main__":
    main()
